### ISSUE TITLE
New repos on Github no longer work by default with MyBinder

### ISSUE THREAD

**Issue by psychemedia** [jupyterhub/binderhub#1168]
New repos created on Github seem to be given the default branchname `main` rather than `master` ([New GitHub Repositories Default to Main Branch](https://www.infoq.com/news/2020/10/github-main-branch/)).

Pasting the repo URL into MyBinder, the build shows a failed build with message: ` "Could not resolve ref for gh:ORG/REPO/master. Double check your URL."`

Relates to: https://github.com/jupyterhub/binderhub/issues/1145

**Comment by sgibson91** [comment]
Hey @psychemedia! 👋 We were just discussing this in Gitter!

I can devote some time to addressing this next week

**TODOs:**

- [ ] Update hard-coded reference to `master` to be `main`
- [ ] Update error message [here](https://github.com/jupyterhub/mybinder.org-deploy/issues/1542#issuecomment-714344364). Adding an extra check for `if unresolved_ref == 'master'` or 'main' and expanding the message in those two cases (main == likely user used default and repo uses master; master == likely old link, repo has been updated to use main)
- [ ] Add a notice box to the mybinder.org homepage template notifying users of the change. [Homepage template](https://github.com/jupyterhub/binderhub/blob/master/binderhub/templates/index.html)

**Comment by psychemedia** [comment]
Would a really quick stop gap be to check for the `Could not resolve ref for gh:ORG/REPO/master` error message and add an additional hit: "Github has changed and in the meantime, we're working on it: for now, do you really mean the `main` branch?"

**Comment by sgibson91** [comment]
Would you like to make that PR? The relevant line is linked in my second TODO point.

**Comment by psychemedia** [comment]
@sgibson I could probably tweak the template addressing point 3, eg add something to tutorial block, but I'm not really set up test anything code wise. eg after `<h4>New to Binder? Get started with a Zero-to`

```
<h4>Seeing a <tt>Could not resolve ref / double check your URL</tt> error? New Github repos use <tt>main</tt> rather than <tt>master</tt> for the the default branch.  Check whether you need to set the branch to <tt>main</tt>.</h4>
```

**Comment by sgibson91** [comment]
@psychemedia I'm co-working with someone who can help with that next week, I specifically meant your quick stop gap fix.

**Comment by psychemedia** [comment]
@sgibson re: the link to where the fix could take place, I think that is an incorrect link (link to help chart discussion issue?)

**Comment by sgibson91** [comment]
Correct :) I've updated my original comment, thank you

**Comment by psychemedia** [comment]
So in my world, a hacky route would go from:

```python
        if ref is None:
            await self.fail("Could not resolve ref for %s. Double check your URL." % key)
            return
```

to:

```python
        if ref is None:
            fail_message = ["Could not resolve ref for %s." % key]
            unresolved_branch = key.split("/")[-1]
            if unresolved_branch == "master":
                 fail_message.append( 'Github recently changed default branches from "master" to "main". Did you mean the "main" branch?')
            elif unresolved_branch == "main":
                 fail_message.append('Github recently changed default branches from "master" to "main". Did you mean the "master" branch?')
            fail_message.append("Double check your URL.")
            await self.fail(" ".join(fail_message))
            return
```

but you probably want something cleaner than that...

But as I say, I'm not really in a position to test it...

**Comment by sgibson91** [comment]
Thank you for the code snippet @psychemedia. I opened PR #1170 but haven't quite managed local testing yet.

**Comment by renefritze** [comment]
Are new gists also affected by this? I've just now tried to use a [new gist](https://gist.github.com/renefritze/57db73707f97ed0bd4eb600a1a6f9ab3) where the binder interface seems stuck on "waiting to build". 
Trying [a gist](https://gist.github.com/renefritze/14c5f2d79694ff746e7b0905a773e03c) I created 7 months ago seems to work fine (as in a jupyterhub instance is spawned).

**Comment by sgibson91** [comment]
@renefritze I'm not sure. As far as I can tell, gists don't have a branch structure so... no? If an old gist launches fine, I'd guess it's some of our more normal, familiar bugs (😅). If you have an ad-blocker enabled, disable it and try launching again?

**Comment by renefritze** [comment]
I tried this with firefox and no plugins. I've now tried to clone both gists to my local machine and both have a master branch checked out afterwards. Should I open another issue then for this?

**Comment by sgibson91** [comment]
Yes I think so. I'm not entirely sure if this is the same problem, but seems related somehow.

**Comment by ncclementi** [comment]
Hi there, I'm trying to get a binder going and I see the same error reported on the initial comment on this issue
```
Could not resolve ref for gh:coiled/dask-mini-tutorial/HEAD. Double check your URL. GitHub recently changed default branches from "master" to "main".
```
![Screen Shot 2021-09-29 at 2 09 35 PM](https://user-images.githubusercontent.com/7526622/135285433-97386ded-0c15-4f35-afe2-1709b6cc7b02.png)

cc: sgibson91  since you address this on https://github.com/jupyterhub/binderhub/pull/1172

**Comment by manics** [comment]
https://github.com/coiled/dask-mini-tutorial/ leads to a 404 page. Is it a private repo?
If you need more help please use https://discourse.jupyter.org/

**Comment by ncclementi** [comment]
@manics I thought it wasn't but I just realized it is. I'm so sorry, I apologized for the inconvenience.
