### ISSUE TITLE
ToDo for beta.mybinder.org

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#12]
# ToDo before beta
## Chris
- [x] Build the Binder diagram
- [x] Finalize new text for main page (under 'how it works', since it is slightly different)
- [x] Make favicon work
- [x] Figure out how to get images inheriting from 'binder-base' to work. Figure out what is actually in that image, and if we can find the source somewhere
- [x] Test a lot of binder repositories to make sure we're fully compatible
- [x] Blog post for the release (#50)

## Yuvi
- [x] Rebuild the UI landing page using HTML/CSS
- [x] Get an IP address for `beta.mybinder.org`
- [x] Fix the progress / logging UX to be understandable
- [x] Not doing for now: ~Set up Prometheus / Grafana for metrics on this (assuming this isn't a lot of work, otherwise we move it to later, but I think it'd be good to start collecting data abt users/downtime ASAP)~
- [x] Make sure that currently existing 'launch binder' buttons work
- [x] Figure out a permalink solution `v2`
- [x] Support non-master refs
- [x] Scale up the beta mybinder deployment (maybe autoscale?) 

## Min
- [x] Add support for anaconda `yml` installs

**Comment by choldgraf** [comment]
Photo for block diagram:

![image](https://cloud.githubusercontent.com/assets/1839645/26015250/1e3f4ca8-3715-11e7-89cf-5c2be708346f.png)

**Comment by choldgraf** [comment]
@yuvipanda I think that we should split up the to-do list above, as it reads more like a general roadmap rather than a "we need to do this before the beta release" list.

I'd propose this:
---
# ToDo before beta
## Chris
- [x] Build the Binder diagram
- [x] Finalize new text for main page (under 'how it works', since it is slightly different)
- [x] Make favicon work

## Yuvi
- [ ] Rebuild the UI landing page using HTML/CSS
- [x] Get an IP address for `beta.mybinder.org`
- [ ] Fix the progress / logging UX to be understandable
- [ ] Set up Prometheus / Grafana for metrics on this (assuming this isn't a lot of work, otherwise we move it to later, but I think it'd be good to start collecting data abt users/downtime ASAP)

## Unassigned
- [ ] Figure out how to get images inheriting from 'binder-base' to work. Figure out what is actually in that image, and if we can find the source somewhere
- [ ] Make sure that currently existing 'launch binder' buttons work
- [ ] Figure out what to do about all the conda stuff
- [ ] Test a lot of binder repositories to make sure we're fully compatible

# ToDo over the course of a month or two
- [ ] Confirm w/ Titus when the workshop is, get them to move it sometime outside of September. (to do after Yuvi meets w/ Tim)
- [ ] Figure out how to shout out to jupyter in the design etc somehow (e.g., maybe a [logo?](https://www.dropbox.com/s/8w8p84h1dzh2ay6/binder.svg?dl=0))
- [ ] Actually make it work with refs other than master
- [ ] Decide whether to use different badges (using same Binder badge for now)
- [ ] Figure out API
- [ ] Figure out a permalink solution `v2`

---
Thoughts?

**Comment by choldgraf** [comment]
OK I moved those points and updated the first comment. Also gonna ping @minrk on this one since he's mentioned here now as well :-)

**Comment by yuvipanda** [comment]
@choldgraf what happened to the unassigned ones? did you just delete them?

**Comment by choldgraf** [comment]
oops no - I put them here: https://github.com/yuvipanda/builderhub/projects/1

I wanted to keep this issue focused on pre-beta items, and we had some in here that weren't pre-beta so I put them in a project as a stopgap measure. How do you want to handle todos? I like projects personally but am happy to just use issues if that's better for you.
