### ISSUE TITLE
ToDo for Binder v0.1beta

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#73]
After many months of hard work it is time to launch the new Binder backend! Let's use this issue to coordinate the last few steps we need to take. @yuvipanda and @freeman-lab correct me if I'm wrong, but here's the list as I see it:

## ToDo
**Tech**
- [x] Set slowspawn timeout to 0 so that pre-built images will launch faster (@yuvipanda)
- [x] Error pages: incl kubernetes full error + check for other miscellaneous errors to catch #91 (@minrk)
- [x] tmpnb auth bug causing people to have to clear their cache (@minrk or @yuvipanda)
- [x] Figure out a UI to create the badges for newly-built binders ( #122 )
- [x] Figure out the URL for the badges ( #122 )
- [x] Make sure that the badge SVG will still link properly so images don't break ( #122 )

**Documentation**
- [x] Documentation on user repo structure (@choldgraf)
- [x] Flow chart on when to use a Dockerfile (@choldgraf @yuvipanda @minrk )
- [x] Templates / best-practices for Dockerfiles (@choldgraf @yuvipanda @minrk )
- [x] Add a little more error handling (@yuvipanda)

**Misc**
- [x] Swap omgwtf to mybinder.org (@yuvipanda)
- [ ] Have a privacy policy (@yuvipanda and @choldgraf)
- [x] ~Deprecate all the old Binder repos to point to the new deployment. (@choldgraf)~
- [x] ~Transfer DNS ownership to Jupyter (@freeman-lab and @choldgraf)~
- [x] Make sure old badge URLs will still work ( #122 )

## Release
- [x] Point `mybinder.org` to the new Binder deployment (@yuvipanda)
- [x] Send out a blog post talking about changes etc (@choldgraf) (handled in another repo)

## Non blocking
- [x] Delete stale users
- [x] UI improvements so it doesn't look like a form (maybe discuss w/ Granger UI team)
- [ ] Get the Binder logo on the notebook pages (@choldgraf)

## Update
Here's a whiteboard from JupyterCon:
<img src="https://user-images.githubusercontent.com/1839645/29754357-59457d6e-8b51-11e7-9a1d-371f56edab3d.jpg" height="400" />

**Comment by yuvipanda** [comment]
I added a couple more.

**Comment by choldgraf** [comment]
@yuvipanda where are we on this one? We discussed making the switch this week but I want to make sure our ducks are in a row before doing this. I've added one or two other things to the list...if you wanna chat about the others lemme know!

**Comment by choldgraf** [comment]
@minrk just merged in a bunch of UI / badge improvements, so we're close to being ready. Some quick loose ends:

@yuvipanda:  what's the status of this one? `Set slowspawn timeout to 0 so that pre-built images will launch faster`

@yuvipanda (w @choldgraf): when do you have time to make the changes necessary to start pointing users to `mybinder.org` instead of `omgwtf`? I can help make DNS changes if need be.

Other than this, the main other thing is to figure out a privacy/anti-abuse policy (see https://github.com/jupyterhub/binderhub/issues/70). For this I think we should have some kind of discussion. Could happen in either #70 or elsewhere. Thoughts?

After these I think we are ready to go.

**Comment by choldgraf** [comment]
done!
